Adding documentation for few functions that are being used in ```Animint2``` package but have not been exported in NAMESPACE of ```ggplot2Animint```
To avoid this error:
```R
checking examples ... ERROR
Running examples in 'animint2-Ex.R' failed
The error most likely occurred in:

> base::assign(".ptime", proc.time(), pos = "CheckExEnv")
> ### Name: animint2dir
> ### Title: Compile and render an animint in a local directory
> ### Aliases: animint2dir animint
>
> ### ** Examples
... 18 lines ...
+                   showSelected="year",
+                   clickSelects="country",
+                   data=WorldBank)+
+        geom_text(aes(fertility.rate, life.expectancy, label=country),
+                  showSelected=c("country", "year"),
+                  data=WorldBank)+
+        make_text(WorldBank, 5, 80, "year")+
+        scale_size_animint(pixel.range=c(2,20), breaks=10^(4:9)))
> animint2dir(gapminder, "WorldBank-viz")
Error: 'plot_theme' is not an exported object from 'namespace:ggplot2Animint'
Execution halted

```

And this one too(in ```animint2``` ):

```R
Missing or unexported objects:
  'ggplot2Animint::guides_geom' 'ggplot2Animint::guides_merge'
  'ggplot2Animint::guides_train' 'ggplot2Animint::plot_theme'
  'ggplot2Animint::stairstep'

```